// Build-time script: injects static, crawlable text into dist/index.html
// after `vite build`. The app is a client-rendered SPA — without this,
// crawlers/agents that don't execute JS (GPTBot, ClaudeBot, PerplexityBot,
// and non-rendering search bots) see two empty <div>s and nothing else.
//
// Run manually with `npm run prerender`, or automatically as part of
// `npm run build`. Idempotent: safe to re-run against the same dist/index.html.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DIST_INDEX = path.join(ROOT, "dist", "index.html");
const DATA_DIR = path.join(ROOT, "public", "data");

const TOP_CITIES_COUNT = 20;

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function loadJson(filename) {
  return JSON.parse(fs.readFileSync(path.join(DATA_DIR, filename), "utf-8"));
}

function buildCountryList(countries) {
  const items = countries
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((c) => `<li>${escapeHtml(c.name)} (${escapeHtml(c.code)})</li>`)
    .join("");
  return `<h2>Countries covered</h2><ul>${items}</ul>`;
}

function buildTopCitiesTable(cities) {
  const top = cities
    .slice()
    .sort((a, b) => b.population - a.population)
    .slice(0, TOP_CITIES_COUNT);
  const rows = top
    .map(
      (c) => `<tr>
        <td>${escapeHtml(c.city)}</td>
        <td>${escapeHtml(c.countryName)}</td>
        <td>${c.population.toLocaleString("en-US")}</td>
        <td>${c.lat.toFixed(4)}, ${c.lng.toFixed(4)}</td>
      </tr>`,
    )
    .join("");
  return `<h2>Largest cities by population</h2>
    <table>
      <thead><tr><th>City</th><th>Country</th><th>Population</th><th>Coordinates</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
}

function buildPrerenderedHtml(countries, cities) {
  const summary = `<p>Geo Explorer is an interactive world map for searching cities and
    countries. It covers ${countries.length} countries and ${cities.length.toLocaleString(
      "en-US",
    )} cities, with population, coordinates, and country border data for each.</p>`;
  return `${summary}${buildCountryList(countries)}${buildTopCitiesTable(cities)}`;
}

function main() {
  if (!fs.existsSync(DIST_INDEX)) {
    throw new Error(`${DIST_INDEX} not found — run \`vite build\` first.`);
  }

  const countries = loadJson("countries.json");
  const cities = loadJson("cities.json");
  const prerenderedHtml = buildPrerenderedHtml(countries, cities);

  const html = fs.readFileSync(DIST_INDEX, "utf-8");
  const startMarker = "<!-- prerender:start (generated by scripts/prerender.mjs, do not edit by hand) -->";
  const endMarker = "<!-- prerender:end -->";
  const startIdx = html.indexOf(startMarker);
  const endIdx = html.indexOf(endMarker);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error("prerender markers not found in dist/index.html — did index.html change?");
  }

  const before = html.slice(0, startIdx + startMarker.length);
  const after = html.slice(endIdx);
  const injectedSection = `\n      <section id="prerendered-content" class="visually-hidden">${prerenderedHtml}</section>\n      `;
  const updated = `${before}${injectedSection}${after}`;

  fs.writeFileSync(DIST_INDEX, updated);
  console.log(
    `Prerendered ${countries.length} countries and ${TOP_CITIES_COUNT} sample cities into dist/index.html`,
  );
}

main();
